import {
  FaArrowLeft,
  FaArrowRight,
  FaCalendar,
  FaChevronLeft,
  FaChevronRight,
  FaDownload,
  FaEnvelope,
  FaFacebookF,
  FaHeart,
  FaInstagram,
  FaLinkedinIn,
  FaPhone,
  FaRegCalendar,
  FaRegClock,
  FaRegEnvelope,
  FaRegFileLines,
  FaRegHeart,
  FaRegUser,
  FaRocket,
  FaUser,
  FaWhatsapp,
  FaXTwitter,
  FaXmark,
} from "react-icons/fa6";

const icons = {
  "arrow-left": FaArrowLeft,
  "arrow-right": FaArrowRight,
  calendar: FaCalendar,
  "chevron-left": FaChevronLeft,
  "chevron-right": FaChevronRight,
  download: FaDownload,
  envelope: FaEnvelope,
  facebook: FaFacebookF,
  heart: FaHeart,
  instagram: FaInstagram,
  linkedin: FaLinkedinIn,
  phone: FaPhone,
  "reg-calendar": FaRegCalendar,
  "reg-clock": FaRegClock,
  "reg-envelope": FaRegEnvelope,
  "reg-file-lines": FaRegFileLines,
  "reg-heart": FaRegHeart,
  "reg-user": FaRegUser,
  rocket: FaRocket,
  user: FaUser,
  whatsapp: FaWhatsapp,
  x: FaXTwitter,
  xmark: FaXmark,
  "fa-arrow-left": FaArrowLeft,
  "fa-arrow-right": FaArrowRight,
  "fa-calendar": FaCalendar,
  "fa-download": FaDownload,
  "fa-envelope": FaEnvelope,
  "fa-facebook-f": FaFacebookF,
  "fa-heart": FaHeart,
  "fa-instagram": FaInstagram,
  "fa-linkedin-in": FaLinkedinIn,
  "fa-phone": FaPhone,
  "fa-rocket": FaRocket,
  "fa-user": FaUser,
  "fa-whatsapp": FaWhatsapp,
  "fa-x-twitter": FaXTwitter,
  "fa-xmark": FaXmark,
};

const Icon = ({ name, className = "", ...props }) => {
  const Component = icons[name] || FaArrowRight;
  return <Component aria-hidden="true" focusable="false" className={className} {...props} />;
};

export default Icon;
